services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=people'
      - 'MYSQL_PASSWORD=example'
      - 'MYSQL_ROOT_PASSWORD=root'
      - 'MYSQL_USER=user'
    ports:
      - '3308:3306'
